### ISSUE TITLE
Deep clone method?

### ISSUE THREAD

**Issue by jjn1056** [Grinnz/Mojo-DOM58#1]
Hi,

I'm using this in Template::Pure and looking for a way to avoid the overhead of parsing the DOM each time the template is called to process (see https://github.com/jjn1056/Template-Pure/blob/master/lib/Template/Pure.pm#L35)

It wasn't such a big issue before, but now that I am adding the ability to prepare the DOM structure and that bit gets reused across the object scope its starting to look like a performance issue.  Ideally I could parse the HTML into a DOM, run my prepare transformations on that, and then clone it for each render request.  

I can see a way to write a clone method here but I was thinking it might be better to have this part of the office API that way if we need to change the underlying data structure we can fix the clone method in the place it belongs, on the object.  I feel like it ideally belongs here since the blessed data structure I should really consider private

So would you be open to adding a $dom->clone or similar method?  This would be a deep clone of the $dom object.  Let me know what youthink?

JohnNap

**Comment by Grinnz** [comment]
Hello,
Please make feature requests in the upstream Mojolicious tracker, as mentioned in https://metacpan.org/pod/Mojo::DOM58#FORK-INFO. If they do not approve I will consider making it an extension. Thanks
